version: '3'

services:
  db:
    image: postgres:16-alpine
    hostname: db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - TZ="Europe/Warsaw"
    ports:
      - '5432:5432'
    volumes:
      - ./db_data:/var/lib/postgresql/data

  ### Go chat server
  server:
    build: ./server
    hostname: server
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_HOST: db
  ### DEV ONLY!!!
  #     LDAP_URL: ldap://openldap:389
    volumes:
      - db:/app/data
      - ./config:/app/config
    ports:
      - 80:80
    depends_on:
      - db

  ### Service which backups database and config
  backup:
    build: ./backup-svc
    hostname: backup
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_HOST: db
    volumes:
      - ./backup:/backup
      - db:/data
      - ./config:/config
    depends_on:
      - db

  ### DEV ONLY!!!
  # ldap:
  #   image: tiredofit/openldap:2.6
  #   hostname: openldap
  #   restart: unless-stopped
  #   environment:
  #     DOMAIN: demo.org
  #     ENABLE_TLS: false
  #     ENABLE_READONLY_USER: true
  #     READONLY_USER_USER: ${LDAP_USER}
  #     READONLY_USER_PASS: ${LDAP_PASS}
  #   ports:
  #     - '389:389'
  #     - '636:636'
  #   volumes:
  #     - ldap-data:/var/lib/openldap
  #     - ldap-cfg:/etc/openldap/slapd.d

  ### DEV ONLY!!!
  # ldap-ui:
  #   image: osixia/phpldapadmin:0.9.0
  #   restart: unless-stopped
  #   environment:
  #     - PHPLDAPADMIN_LDAP_HOSTS=openldap
  #     - PHPLDAPADMIN_HTTPS=false
  #   ports:
  #     - '8001:80'

  ### DEV ONLY!!!
  # db-ui:
  #   image: dpage/pgadmin4:8.2
  #   restart: unless-stopped
  #   environment:
  #     - PGADMIN_DISABLE_POSTFIX=true
  #     - PGADMIN_DEFAULT_EMAIL=tmp@tmp.tmp
  #     - PGADMIN_DEFAULT_PASSWORD=tmp
  #     - PGADMIN_CONFIG_SERVER_MODE=False
  #   ports:
  #     - '8000:80'
  #

volumes:
  db:
    driver: local
  ### DEV ONLY!!!
  # ldap-data:
  #   driver: local
  # ldap-cfg:
  #   driver: local
